1.Python program to add two Matrices

In [1]:
X = [[1,2,3],[4 ,5,6],[7 ,8,9]]
 
Y = [[9,8,7],[6,5,4],[3,2,1]]
 
result = [[0,0,0],[0,0,0],[0,0,0]]

In [4]:
for i in range(len(X)):
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]
 
    for r in result:
        print(r,end=" ")

[10, 10, 10] [10, 10, 10] [10, 10, 10] [10, 10, 10] [10, 10, 10] [10, 10, 10] [10, 10, 10] [10, 10, 10] [10, 10, 10] 

2.Python program to multiply two matrices

In [5]:
for i in range(len(X)):
    for j in range(len(X[0])):
        result[i][j] = X[i][j] * Y[i][j]
 
    for r in result:
        print(r,end=" ")

[9, 16, 21] [10, 10, 10] [10, 10, 10] [9, 16, 21] [24, 25, 24] [10, 10, 10] [9, 16, 21] [24, 25, 24] [21, 16, 9] 

3.Python program for Matrix Product

In [8]:
for i in range(len(X)):
    for j in range(len(X[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][j] * Y[i][j]
 
    for r in result:
        print(r,end=" ")

[36, 64, 84] [24, 25, 24] [21, 16, 9] [36, 64, 84] [96, 100, 96] [21, 16, 9] [36, 64, 84] [96, 100, 96] [84, 64, 36] 

4.Adding and Subtracting Matrices in Python

In [9]:
import numpy as np
  
A = np.array([[1, 2], [3, 4]])
  
B = np.array([[4, 5], [6, 7]])
  
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
  
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


5.Transpose a matrix in Single line in Python

In [10]:
matrix=[(1,2,3),(4,5,6),(7,8,9),(10,11,12)]
for row in matrix:
    print(row)
print("\n")
t_matrix = zip(*matrix)
for row in t_matrix:
    print(row)

(1, 2, 3)
(4, 5, 6)
(7, 8, 9)
(10, 11, 12)


(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


6.Python | Matrix creation of n*n

In [11]:
N = 4

print("The dimension : " + str(N))

res = [list(range(1 + N * i, 1 + N * (i + 1)))
    for i in range(N)]
print("The created matrix of N * N: " + str(res))

The dimension : 4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


7.Python | Get Kth Column of Matrix

In [12]:
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]

print("The original list is : " + str(test_list))

K = 2

res = [sub[K] for sub in test_list]

print("The Kth column of matrix is : " + str(res))

The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of matrix is : [6, 10, 5]


8.Python – Vertical Concatenation in Matrix

In [13]:
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
  
print("The original list : " + str(test_list))

res = []
N = 0
while N != len(test_list):
    temp = ''
    for idx in test_list:
        try: temp = temp + idx[N]
        except IndexError: pass
    res.append(temp)
    N = N + 1
  
res = [ele for ele in res if ele]
 
print("List after column Concatenation : " + str(res))

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


9.Python program to check if a string is palindrome or not

In [14]:
def isPalindrome(s):
    return s == s[::-1]
 
s = "malayalam"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


10.Python program to check whether the string is Symmetrical or Palindrome

In [16]:
string = str(input("Enter the word:  "))
half = int(len(string) / 2)
 
if len(string) % 2 == 0:
    first_str = string[:half]
    second_str = string[half:]
else: 
    first_str = string[:half]
    second_str = string[half+1:]

if first_str == second_str:
    print(string, 'string is symmertical')
else:
    print(string, 'string is not symmertical')

if first_str == second_str[::-1]:
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')

Enter the word:  Suresh
Suresh string is not symmertical
Suresh string is not palindrome
